dist: trusty
sudo: required

language: node_js

node_js:
  - "10"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  code_climate:
    repo_token: $CODE_COVERAGE_TOKEN

cache:
  directories:
    - ./node_modules

branches:
  only:
    - master

install:
  - npm install
  - npm install -g @angular/cli codeclimate-test-reporter

#before_script:
#  - npm install -g @angular/cli

script:
  - ng lint
  - npm run test-headless
  - npm run e2e-headless
  - ng build --prod --base-href https://tiamat-azure.github.io/angular-brotli/
  #- node compress.js

after_script:
  - codeclimate-test-reporter < ./coverage/angular-brotli/lcov.info

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist/angular-brotli
    on:
      branch: master
  - provider: surge
    project: ./dist/angular-brotli/
    domain: angular-brotli.surge.sh
    on: master
  skip_cleanup: true
